<?php


define('ROOT', __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR);
define('APP', ROOT.'app'.DIRECTORY_SEPARATOR);
define('CONTROLLERS', APP.'Controllers'.DIRECTORY_SEPARATOR);
define('CORE', APP.'Core'.DIRECTORY_SEPARATOR);
define('MODELS', APP . 'Models' . DIRECTORY_SEPARATOR);
define('SERVICES', APP . 'Services' . DIRECTORY_SEPARATOR);
define('VIEWS', APP . 'Views' . DIRECTORY_SEPARATOR);
